# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Campinas"
email: "contato@gdg-campinas.org"
description: "O DevFest é uma conferência te tecnlogia voltada para interessados no assunto de Campinas e região."
baseurl: "/devfest"
url: "https://gdg-campinas.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-campinas.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
mapsApiKey: "AIzaSyBKggjiyNZRv2LMI86wSOAu2f2yZzUXArI"

aboutEvent:
  title: "SOBRE O DEVFEST"
  content: "O DevFest é uma conferência te tecnlogia voltada para interessados no assunto de Campinas e região."
aboutGDG:
  title: "O QUE É O GDG?"
  content: "O GDG Campinas é parte de um programa do Google (Google Developer Group) sendo atualmente 1 de mais de 675 comunidades espalhadas pelo mundo. 
  <br> Possuimos o objetivo de proporcionar ambientes de compartilhamento de conhecimento sobre os mais diversos assuntos que permeiam o desenvolvimento de um produto (software), da maneira mais acessível a todos que estiverem dispostos a aprender e compartilhar."

# Organizer Info
organizerName: "GDG Campinas"
organizerAlternateName: "Google Developer Group Campinas"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contato@gdg-campinas.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.meetup.com/gdgcampinas/"

# Head
metaKeywords: "event, gdg, devfest, data, fest, google, programming, developers, campinas"
twitterAccount: "@gdgcampinas"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/HZdUM2UqPVusZci12"
c4pTitle: "Submeta um conteúdo"
c4pDescription: "Se tiver interesse em compartilhar seu conhecimento com a comunidade submeta uma PALESTRA, se voluntarie como MENTOR e/ou solicite um estande para a sua COMUNIDADE"
c4sponsorsUrl: "https://docs.google.com/presentation/d/1IyQCkhEZjP_dpwPdm61BaqXHdFBICdKUHq_n5xTNi-0/edit#slide=id.g35f391192_00"
c4mentorUrl: "https://goo.gl/forms/qIcrpQv6mXIyJ2V33"
c4mentorTitle: "Inscreva-se para mentoria"
c4mentorDescription: ""

# Navigation
navigationLinks:
 - {permalink: "/", text: "Principal"}
#  - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Grade"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/mentors/", text: "Mentoria"}
 - {permalink: "/kids/", text: "Trilha Kids"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
 - {link: "https://goo.gl/forms/giwSyQAtqV4kUgHC3", text: "Torne-se um membro"}
 - {permalink: "/team/", text: "Time"}
 
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364
", text: "Ingressos"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364
", text: "Ingressos"}

# Hero Block
heroImage: "hero.png"
heroTitle: "DevFest <typeout> 2017"
eventDate: "4 de Novembro de 2017"
typeoutTextValues: '"", "Campinas"'
typeoutFallback: "Campinas"
heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Ingressos"}

# About Block
# aboutTitle: "About GDG DevFest"
# aboutBlock:
#  - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
#  - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "", info: "participantes", detail: "de Campinas e região"}
 - {count: "9", specialCharacter: "+", info: "horas", detail: "de muito networking e conteúdo de altíssima qualidade"}
 - {count: "46", specialCharacter: "", info: "palestrantes", detail: "referências nos assuntos"}
 - {count: "5", specialCharacter: "", info: "trilhas", detail: "simultâneas"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "background-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Destaques"
rockstarLinkEnabled: true
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Vitória Concept"
eventLocationLink: "http://www.vitoriahoteis.com.br/pt/hotel-concept-campinas-o-hotel/"
eventStreetAddress: "Av. José de Souza Campos, 425"
eventAddressLocality: "Campinas"
eventAddressLocalityRegion: "Hotel Vitória Concept"
eventPostalCode: "13092-123"
eventAddressCountry: "Brasil"
eventStartTime: ""
eventDoorTime: ""
eventEndTime: ""
eventPlaceCoordinates: "-22.902318, -47.048125"
mapCenterCoordinates: "-22.902318, -47.048125"
mapMobileCenterCoordinates: "-22.902318, -47.048125"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_campinas_0.jpg"
venueSmallImage1: "venue_campinas_1.jpg"
venueSmallImage2: "venue_campinas_2.jpg"
venueSmallImage3: "venue_campinas_3.jpg"
venueTitle: "Vitória Concept"
venueFeatures: ["Hotel"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Esperamos por você!"
twitterHashTag: "devfestcampinas"
twitterFeed: "<< twitter_feed_url >>"
twitterHomeUrl: "https://twitter.com/gdgcampinas"

# Partners Block
organizersTitle: "Realização"
partnersTitle: "Patrocínio"
partnersC4sponsorsButton: "Torne-se um patrocinador"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Incluso: Acesso as 5 trilhas de conteúdo, estandes, sorteios e coffees.<br>
Membros do GDG Campinas tem desconto de 20% em todos os lotes."
ticketsOffers:
 -
  name: "Ligeirinho"
  price: "95,00"
  priceCurrency: "R$"
  ticketsNumber: "TBD"
  # ribbon: "-5%"
  buyButtonLink: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "26/09/2017T17:00"
  validThrough: "08/10/2017T00:00"
  soldOut: true
  soldOutText: "Esgotado"
  disabled: true
 -
  name: "Lebre"
  price: "115,00"
  priceCurrency: "R$"
  ticketsNumber: "TBD"
  # ribbon: "-20%"
  # featured: true
  buyButtonLink: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "08/10/2017T00:00"
  validThrough: "29/10/2017T00:00"
  featured: false
  disabled: true
  soldOut: true
  soldOutText: "Esgotado"
 -
  name: "Lebre"
  price: "75,00"
  priceCurrency: "R$"
  ticketsNumber: "TBD"
  # ribbon: "-20%"
  # featured: true
  buyButtonLink: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "08/10/2017T00:00"
  validThrough: "29/10/2017T00:00"
  featured: true
 -
  name: "Kids"
  price: "38,00"
  priceCurrency: "R$"
  ticketsNumber: "TBD"
  # ribbon: "-20%"
  # featured: true
  buyButtonLink: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "27/10/2017T00:00"
  validThrough: "03/11/2017T00:00"
  featured: true
 -
  name: "Tartaruga"
  price: "95,00"
  priceCurrency: "R$"
  ticketsNumber: "TBD"
  buyButtonLink: "https://www.eventbrite.com.br/e/devfest-campinas-2017-tickets-38297336364"
  buyButtonText: "Comprar"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "29/10/2017T00:00"
  validThrough: "30/11/2017T00:00"
  disabled: false
  featured: true
  # soldOut: true
  # soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDG-CampinasOrg", icon: "google-plus"}
 - {link: "https://twitter.com/gdgcampinas", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgcampinas/", icon: "facebook"}
 - {link: "https://www.linkedin.com/company-beta/15240699/", icon: "linkedin"}
#  - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/gdgcampinas/", text: "Meetup"}
   - {link: "https://www.facebook.com/groups/gdgcampinas/", text: "Grupo Facebook"}
   - {link: "https://chat.whatsapp.com/H7KW7cqz9pVCbw9onN48qZ", text: "Whatsapp"}
   - {link: "https://devfestcampinas.firebaseapp.com/", text: "DevFest Campinas 2016"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:contato@gdg-campinas.org", text: "contato@gdg-campinas.org"}
#  -
#   title: "FAQ"
#   links:
#    - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true
emptySessionTitle: "A definir"
scheduleWarning: "A grade está sujeita a mudanças sem aviso prévio"
showMentorSessions: false

# Team Block
teamBlockTitle: "Quem somos"
aboutUs: "O GDG Campinas é parte de um programa do Google (Google Developer Group) sendo atualmente 1 de mais de 675 comunidades espalhadas pelo mundo. 
  <br> Possuimos o objetivo de proporcionar ambientes de compartilhamento de conhecimento sobre os mais diversos assuntos que permeiam o desenvolvimento de um produto (software), da maneira mais acessível a todos que estiverem dispostos a aprender e compartilhar."
teamOrganizerTitle: "Organizadores"

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
